### ISSUE TITLE
도커를 활용한 CI/CD 기본 환경 세팅

### ISSUE THREAD

**Issue by dyk000825** [YunTaeHyeon/2024-capstone-fashion#14]
-CI 구축 

먼저 간단한 기능과 테스트 코드를 가지고 있는 스프링 프로젝트를 생성하고 깃허브 레포지토리와 연동합니다. 그리고 .github 디렉토리를 만들고 그 안에 workflow 디렉토리를 만든 후 그 안에 yaml 파일을 만들어서 원하는 workflow를 생성할 수 있습니다. 혹은 깃허브 상단의 Actions에서 new workflow를 통해 workflow를 가져올 수 있습니다.

-CD 구축
EC2 인스턴스를 public subnet에 생성하고 탄력적 ip를 연결합니다.
EC2 인스턴스에 도커를 설치합니다.
로컬에서 rsa 키를 생성합니다.
rsa 퍼블릭 키를 EC2 서버의 .ssh/authorized_keys 파일에 붙여넣습니다.
rsa 프라이빗 키를 깃허브 액션의 secrets에 등록합니다.
host, username, port도 같이 등록해줍니다.
yml 파일을 작성해줍니다.

이러한 과정을 거치면 컨테이너를 실행만 시켜도 서버가 자동 실행됩니다.
자세한 내용은 밑의 링크를 통해서 참고하면 됩니다.

**Comment by dyk000825** [comment]
https://growth-coder.tistory.com/224
https://growth-coder.tistory.com/220

**Comment by YunTaeHyeon** [comment]
AWS를 사용한다는 가정하에 있는 듯 해서 개발 후 서버에 올릴 때 필요할 것 같네요

**Comment by YunTaeHyeon** [comment]
GCP를 활용하여 완료
