### ISSUE TITLE
Spring Data JPA의 메서드 인식 버그

### ISSUE THREAD

**Issue by HYEON-CODE** [YunTaeHyeon/2024-capstone-fashion#195]
## 어떤 기능인가요?

> Spring Data JPA의 메서드이 안됨, 언더바로 추측

## 작업 상세 내용

- [x] 도메인 category_id -> categoryId 로 수정
- [x] 다른 모든 같은 단어도 수정

**Comment by YunTaeHyeon** [comment]
문제 생겨 제가 수정했습니다.
