### ISSUE TITLE
랭킹 시스템 논의

### ISSUE THREAD

**Issue by YunTaeHyeon** [YunTaeHyeon/2024-capstone-fashion#9]

**Comment by YunTaeHyeon** [comment]
랭킹이 유저의 등급이니까
랭킹은 한달마다 업데이트

한달마다 업데이트 하는 이유: 트렌드 반영 가능, 새로운 유저와 오래된 유저간 간격을 좁힐 수 있음

**Comment by YunTaeHyeon** [comment]
-랭킹 기준에 팔로우는 제외(매달 반영해야 하기 때문)

-랭킹 공식을 정의
  별점 받은 개수, 별점 수치(중요)
 
  예시) 5.0점 1명 , 4.9점 100명이 있을 때 4.9점이 더 상위 랭크에 있어야 함.
           4.8점 100명, 4.9점 50명 있으면 누가 더 상위 랭크에 있어야 하는가?

해결 방안: 1. 별점 개수 가중치 사용 - 별점을 받은 개수로 유저를 정렬하여 퍼센트 별로 가중치 부여
                2. 평균 별점을 구하고 그 평균에서 각 유저의 편차를 가중치로 사용

Todo: 랭킹 정산시에 한달 단위로 게시물 자르고 정렬하여 계산해야 함

**Comment by dyk000825** [comment]
게시물3개 이상, 게시물당 최소 좋아요 10개 이상 사람들 중에서만 평균 별점으로 랭킹 선정한다. 표본이 적기 때문에 별점 1점이 크게 작용할 수 있으므로 별점 1점은 0.5명으로 취급하여 평균 별점 설정한다. 게시물의3개 이상 시 추가로 게시물 1개 올릴때마다 전체 평균 별점의 1프로의 가중치를 부여한다. 이에 따라 각 카테고리별 랭킹을 각각의 게시판에서 설정하여 보여준다.
